@startuml

class Animal
{

}
class Mammal
{

}
class Fish
{

}
class Bird
{

}

Animal <|-- Mammal

Animal <|-- Fish
Animal <|-- Bird

Mammal <|.. John
Mammal <|.. Clara

Fish <.. Nemo
Fish <.. Dora

           
@enduml